question_data = [
    {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
     "question": "American rapper Dr. Dre actually has a Ph.D. doctorate.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "The logo for Snapchat is a Bell.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Geography", "type": "boolean", "difficulty": "easy",
     "question": "There is a city called Rome in every continent on Earth.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"category": "Entertainment: Film", "type": "boolean", "difficulty": "easy",
     "question": "Samuel L. Jackson had the words, &#039;Bad Motherf*cker&#039; in-scripted on his lightsaber during the filming of Star Wars.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "boolean",
     "difficulty": "easy",
     "question": "In the &quot;Toaru Kagaku no Railgun&quot; anime,  espers can only reach a maximum of level 6 in their abilities.",
     "correct_answer": "False",
     "incorrect_answers": [
         "True"]},
    {"category": "Sports", "type": "boolean", "difficulty": "easy",
     "question": "Roger Federer is a famous soccer player.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science & Nature", "type": "boolean", "difficulty": "easy",
     "question": "An exothermic reaction is a chemical reaction that releases energy by radiating electricity.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy",
     "question": "The ghosts in &quot;Pac-Man&quot; and &quot;Ms. Pac-Man&quot; have completely different behavior.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy",
     "question": "There are 2 player roles in Trouble in Terrorist Town.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Entertainment: Video Games", "type": "boolean",
     "difficulty": "easy",
     "question": "&quot;Resident Evil 7&quot; is the first first-person Resident Evil game.", "correct_answer": "False",
     "incorrect_answers": ["True"]}]
